//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eContract.DDP.Jobs.FerreroSaleData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FerreroSaleData.ISaleData")]
    public interface ISaleData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/DoWork", ReplyAction="http://tempuri.org/ISaleData/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/GetSKUData", ReplyAction="http://tempuri.org/ISaleData/GetSKUDataResponse")]
        System.Data.DataTable GetSKUData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/GetRegionData", ReplyAction="http://tempuri.org/ISaleData/GetRegionDataResponse")]
        System.Data.DataTable GetRegionData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/GetCityData", ReplyAction="http://tempuri.org/ISaleData/GetCityDataResponse")]
        System.Data.DataTable GetCityData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/GetShipToData", ReplyAction="http://tempuri.org/ISaleData/GetShipToDataResponse")]
        System.Data.DataTable GetShipToData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/GetSoldToData", ReplyAction="http://tempuri.org/ISaleData/GetSoldToDataResponse")]
        System.Data.DataTable GetSoldToData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/GetOrderTypeData", ReplyAction="http://tempuri.org/ISaleData/GetOrderTypeDataResponse")]
        System.Data.DataTable GetOrderTypeData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/GetSKUPriceData", ReplyAction="http://tempuri.org/ISaleData/GetSKUPriceDataResponse")]
        System.Data.DataTable GetSKUPriceData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/GetWarehouseData", ReplyAction="http://tempuri.org/ISaleData/GetWarehouseDataResponse")]
        System.Data.DataTable GetWarehouseData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleData/GetStateData", ReplyAction="http://tempuri.org/ISaleData/GetStateDataResponse")]
        System.Data.DataTable GetStateData();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaleDataChannel : eContract.DDP.Jobs.FerreroSaleData.ISaleData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaleDataClient : System.ServiceModel.ClientBase<eContract.DDP.Jobs.FerreroSaleData.ISaleData>, eContract.DDP.Jobs.FerreroSaleData.ISaleData {
        
        public SaleDataClient() {
        }
        
        public SaleDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaleDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Data.DataTable GetSKUData() {
            return base.Channel.GetSKUData();
        }
        
        public System.Data.DataTable GetRegionData() {
            return base.Channel.GetRegionData();
        }
        
        public System.Data.DataTable GetCityData() {
            return base.Channel.GetCityData();
        }
        
        public System.Data.DataTable GetShipToData() {
            return base.Channel.GetShipToData();
        }
        
        public System.Data.DataTable GetSoldToData() {
            return base.Channel.GetSoldToData();
        }
        
        public System.Data.DataTable GetOrderTypeData() {
            return base.Channel.GetOrderTypeData();
        }
        
        public System.Data.DataTable GetSKUPriceData() {
            return base.Channel.GetSKUPriceData();
        }
        
        public System.Data.DataTable GetWarehouseData() {
            return base.Channel.GetWarehouseData();
        }
        
        public System.Data.DataTable GetStateData() {
            return base.Channel.GetStateData();
        }
    }
}
